- hosts: web
  gather_facts: no
  sudo: yes

  tasks:
    - name: Install NGINX
      apt: >
        cache_valid_time=3600
        update_cache=yes
        state=latest
        name=nginx
      tags: server